monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-debug.log"
            level: debug
            channels: ['!event', '!doctrine', '!cache']
        error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
            channels: [ '!event', '!doctrine', '!cache' ]