pimcore_data_hub:
    configurations:
        product:
            general:
                type: dataImporterDataObject
                name: product
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1765571743
                createDate: 1765566720
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: product/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: product
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '0'
                        attributeName: productId
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: findParent
                    settings:
                        findStrategy: attribute
                        attributeDataObjectClassId: line
                        attributeName: key
                        attributeLanguage: ''
                        dataSourceIndex: '1'
                        fallbackPath: /Products
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: Key
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Product ID'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: productId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Description
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: en
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: UPC
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: upc
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
