services:
    _defaults:
        autowire: true
        autoconfigure: true

    # define own price system service and configure options for attribute name and price object class
#    app.default_price_system:
#        class: App\Ecommerce\Pricing\EclipsePriceSystem

    # define own availability system service and configure options for attribute name and price object class
#    app.default_availability_system:
#        class: App\Ecommerce\Availability\EclipseAvailabilitySystem

#pimcore:
#    models:
#        class_overrides:
#            Pimcore\Model\DataObject\Product: App\Model\Product\Product
#            Pimcore\Model\DataObject\Category: App\Model\Product\Category

pimcore_ecommerce_framework:
    pimcore:
        menu:

            # Enabling/Disabling Pricing Rules menu entry. User specific settings can be done via permissions.
            pricing_rules:
                enabled:              false

            # Configuring order list menu - enabling/disabling and defining route of order list to inject custom implementations of order backend.
            order_list:
                enabled:              false
                route:                pimcore_ecommerce_backend_admin-order_list
                path:                 null

    # Configuration of price systems - key is name of price system
#    price_systems:
#        default:
#            # Price system defined and configured as container service
#            id: app.default_price_system
#
#    availability_systems:
#        default:
#            id: app.default_availability_system

    cart_manager:
        tenants:
            # defaults for all cart managers
            default:
                # configuration for carts - the following values are set by default and can be omitted
                cart:
                    # options passed to cart factory, e.g. the cart class (available options vary by factory implementation)
                    #factory_id: App\Ecommerce\CartManager\CartFactory
                    factory_options:
                        cart_class_name: App\Cart\Cart
                        guest_cart_class_name: App\Cart\SessionCart

#            punchout:
#                cart:
#                    factory_options:
#                        cart_class_name: App\Cart\SessionCart
#                        guest_cart_class_name: App\Cart\SessionCart
