services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Provider\:
        resource: '../../src/Provider'

    McSupply\EcommerceBundle\Provider\User\CustomerProviderInterface:
        '@App\Provider\User\CustomerProvider'

    McSupply\EcommerceBundle\Provider\OnlineStore\OnlineStoreProviderInterface:
        '@App\Provider\OnlineStore\OnlineStoreProvider'

    McSupply\EcommerceBundle\Provider\Company\BranchProviderInterface:
        '@App\Provider\Company\BranchProvider'

    McSupply\EcommerceBundle\Provider\Company\AccountProviderInterface:
        '@App\Provider\Company\AccountProvider'

    McSupply\EcommerceBundle\Provider\Product\ProductTypeProviderInterface:
        '@App\Provider\Product\ProductTypeProvider'

    McSupply\EcommerceBundle\Provider\Shipping\ShipMethodProviderInterface:
        '@App\Provider\Shipping\ShipMethodProvider'

    McSupply\EcommerceBundle\Provider\Payment\PaymentMethodProviderInterface:
        '@App\Provider\Payment\PaymentMethodProvider'

    McSupply\EcommerceBundle\Provider\Address\AddressProviderInterface:
        '@App\Provider\Address\AddressProvider'