imports:
    - { resource: ../../config.yaml }

pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: "symfony-config"

framework:
    mailer:
        transports:
            main: "smtp://%env(SMTP_DOMAIN)%:25"
