pimcore:
    perspectives:
        definitions:
            default:
                elementTree:
                    -
                        type: objects
                        position: left
                        expanded: false
                        hidden: false
                        sort: 0
                        treeContextMenu:
                            object:
                                items:
                                    add: true
                                    addFolder: true
                                    importCsv: true
                                    cut: true
                                    copy: true
                                    paste: true
                                    delete: true
                                    rename: true
                                    reload: true
                                    publish: true
                                    unpublish: true
                                    searchAndMove: true
                                    lock: true
                                    unlock: true
                                    lockAndPropagate: true
                                    unlockAndPropagate: true
                                    changeChildrenSortBy: true
                    -
                        type: assets
                        position: left
                        expanded: false
                        hidden: false
                        sort: 1
                    -
                        type: documents
                        position: left
                        expanded: false
                        hidden: false
                        sort: 2
                iconCls: pimcore_nav_icon_perspective
                icon: null
                dashboards:
                    predefined:
                        welcome:
                            positions:
                                -
                                    -
                                        id: 1
                                        type: pimcore.layout.portlets.modificationStatistic
                                        config: null
                                    -
                                        id: 2
                                        type: pimcore.layout.portlets.modifiedAssets
                                        config: null
                                -
                                    -
                                        id: 3
                                        type: pimcore.layout.portlets.modifiedObjects
                                        config: null
                                    -
                                        id: 4
                                        type: pimcore.layout.portlets.modifiedDocuments
                                        config: null
                toolbar:
                    file:
                        hidden: false
                        items:
                            perspectives: true
                            dashboards: true
                            openDocument: true
                            openAsset: true
                            openObject: true
                            searchReplace: true
                            schedule: true
                            seemode: true
                            closeAll: true
                            help: true
                            about: true
                    marketing:
                        hidden: false
                        items:
                            reports: true
                            tagmanagement: true
                            targeting: true
                            seo:
                                hidden: false
                                items:
                                    documents: true
                                    robots: true
                                    httperrors: true
                    extras:
                        hidden: false
                        items:
                            glossary: true
                            redirects: true
                            translations: true
                            recyclebin: true
                            plugins: true
                            notesEvents: true
                            applicationlog: true
                            gdpr_data_extractor: true
                            emails: true
                            maintenance: true
                            systemtools:
                                hidden: false
                                items:
                                    requirements: true
                    settings:
                        hidden: false
                        items:
                            customReports: true
                            marketingReports: true
                            documentTypes: true
                            predefinedProperties: true
                            predefinedMetadata: true
                            system: true
                            appearance: true
                            website: true
                            users:
                                hidden: false
                                items:
                                    users: true
                                    roles: true
                            thumbnails: true
                            objects:
                                hidden: false
                                items:
                                    classes: true
                                    fieldcollections: true
                                    objectbricks: true
                                    quantityValue: true
                                    classificationstore: true
                                    bulkExport: true
                                    bulkImport: true
                            routes: true
                            cache:
                                hidden: false
                                items:
                                    clearAll: true
                                    clearData: true
                                    clearSymfony: true
                                    clearOutput: true
                                    clearTemp: true
                            adminTranslations: true
                            tagConfiguration: true
                            perspectiveEditor: true
                    search:
                        hidden: false
                        items:
                            quickSearch: true
                            documents: true
                            assets: true
                            objects: true
                    datahub:
                        hidden: false
