pimcore:
    objects:
        select_options:
            definitions:
                ProductStatus:
                    id: ProductStatus
                    group: ''
                    adminOnly: false
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions:
                        -
                            value: Stock
                            label: Stock
                            name: ''
                        -
                            value: NonStock
                            label: 'Non Stock'
                            name: ''
                        -
                            value: Delete
                            label: Delete
                            name: ''
                        -
                            value: Purge
                            label: Purge
                            name: ''
