pimcore:
    objects:
        select_options:
            definitions:
                ShipMethodType:
                    id: ShipMethodType
                    group: ''
                    adminOnly: false
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions:
                        -
                            value: B
                            label: Bid
                            name: ''
                        -
                            value: A
                            label: 'Will Call'
                            name: ''
                        -
                            value: S
                            label: Shipping
                            name: ''
