_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: attribute

mcsupply_ecommerce:
    resource: "@McSupplyEcommerceBundle/config/routing.yaml"

customer-logout:
    path: '/customer/logout'

ux_live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: /_components
