imports:
    - { resource: 'ecommerce/providers.yaml' }
    - { resource: 'theme/theme.yaml' }

parameters:
    kernel_secret_file_fallback: '/run/secrets/kernel-secret'
    secret: '%env(file:default:kernel_secret_file_fallback:KERNEL_SECRET_FILE)%'

    # These are default values for connecting to the database/Redis cache that the Docker build sometimes requires to be set.
    # Once the app is actually running, they will be replaced with actual values.
    env(DATABASE_HOST): ''
    env(DATABASE_PORT): 0
    env(DATABASE_NAME): ''
    env(DATABASE_USER): ''
    env(DATABASE_PASSWORD): ''
    env(DATABASE_SERVER_VERSION): '0.0.0'
    env(REDIS_DB): "0"
    env(REDIS_SESSION_DB): "0"
    env(REDIS_HOST): 'redis://redis'

    # customize the full path to external executables
    # normally they are auto-detected by `which program` or auto-discovered in the configured path in
    # System Settings -> General -> Additional $PATH variable
    # but in general it's a good idea to have your programs in your $PATH environment variable (system wide)

    #pimcore_executable_composer: php /opt/vendor/bin/composer.phar
    #pimcore_executable_html2text: /usr/local/html2text/bin/html2text
    #pimcore_executable_soffice: /opt/libreoffice/bin/soffice
    #pimcore_executable_gs: /opt/ghostscript/bin/gs
    #pimcore_executable_pdftotext: /opt/tools/pdftotext
    #pimcore_executable_xvfb-run: /opt/tools/xvfb-run
    #pimcore_executable_pngcrush: /opt/tools/pngcrush
    #pimcore_executable_zopflipng: /opt/tools/zopflipng
    #pimcore_executable_pngout: /opt/tools/pngout
    #pimcore_executable_advpng: /opt/tools/advpng
    #pimcore_executable_cjpeg: /opt/tools/cjpeg
    #pimcore_executable_jpegoptim: /opt/tools/jpegoptim
    #pimcore_executable_php: /usr/local/custom-php/bin/php
    #pimcore_executable_nice: /opt/tools/nice
    #pimcore_executable_nohup: /opt/tools/nohup
    #pimcore_executable_ffmpeg: /opt/tools/ffmpeg
    #pimcore_executable_exiftool: /opt/tools/exiftool
    #pimcore_executable_wkhtmltoimage: /usr/local/bin/wkhtmltoimage
    #pimcore_executable_timeout: /usr/bin/timeout
    #pimcore_executable_facedetect: /usr/bin/facedetect
    # graphviz
    #pimcore_executable_dot: /usr/bin/dot

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    App\OptionProvider\:
        resource: '../src/OptionProvider'

    App\EventListener\:
        resource: '../src/EventListener'

    App\EventListener\AdminFileLoaderEventListener:
        tags:
            - {
                name: kernel.event_listener,
                event: pimcore.bundle_manager.paths.js,
                method: addJSFiles,
            }
            - {
                name: kernel.event_listener,
                event: pimcore.bundle_manager.paths.css,
                method: addCSSFiles,
            }

    App\ExpressionLanguage\BasicExpressionProvider:
        tags:
            - { name: 'pimcore.calculated_value.expression_language_provider' }