pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        valid_languages:
            - en_US
        fallback_languages:
            en_US: ''
        required_languages:
            - ''
        default_language: en_US
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized: {  }
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
